apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: k8s-argocd-image-updater
  annotations:
    github.com/project-slug: mattjmorrison-homelab/k8s-argocd-image-updater
spec:
  type: image-updater
  owner: mattjmorrison-homelab
  system: argocd
