apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-image-updater-zot-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: argocd-image-updater-zot-creds
    creationPolicy: Owner
    template:
      data:
        creds: "k8s-argocd-image-updater:{{ "{{" }} .password {{ "}}" }}"
  data:
    - secretKey: password
      remoteRef:
        key: homelab/service/k8s-zot/k8s-argocd-image-updater/zot-pull
        property: value
